/**
 * Shared environment variable loader for UAT scripts
 * Loads .env files in priority order without overwriting existing process.env
 * Author: Generated by Claude Code
 * Date: 2026-08-31
 */

import { config } from 'dotenv'
import { existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const projectRoot = join(__dirname, '../..')

/**
 * Load environment variables from .env files
 * Priority (lowest to highest):
 * 1. .env (base defaults)
 * 2. .env.local (local overrides)
 * 3. .env.e2e.local (E2E/UAT config)
 * 4. process.env (shell/system vars - highest priority)
 */
export function loadEnv() {
  const envFiles = [
    join(projectRoot, '.env'),
    join(projectRoot, '.env.local'),
    join(projectRoot, '.env.e2e.local'),
  ]

  // Load in reverse order so later files don't override earlier ones
  // dotenv won't overwrite existing process.env vars by default
  envFiles.reverse().forEach(file => {
    if (existsSync(file)) {
      config({ path: file })
    }
  })
}

/**
 * Validate required environment variables for Supabase operations
 * @param {Object} options - Validation options (for backwards compatibility)
 * @returns {Object} Validated config or exits process
 */
export function validateEnv(options = {}) {
  const errors = []

  // Supabase URL (accept either format)
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL

  if (!supabaseUrl) {
    errors.push('SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL is required')
    errors.push('  Add it to .env.e2e.local')
    errors.push('  Get it from: Supabase Dashboard > Project Settings > API > Project URL')
  }

  // Service Role Key (server-side only)
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    errors.push('SUPABASE_SERVICE_ROLE_KEY is required')
    errors.push('  Add it to .env.e2e.local')
    errors.push('  Get it from: Supabase Dashboard > Project Settings > API > service_role key')
    errors.push('  ⚠️  WARNING: NEVER expose this key in client-side code')
  }

  if (errors.length > 0) {
    console.error('❌ ERROR: Missing required environment variables')
    console.error('')
    errors.forEach(err => console.error(err))
    console.error('')
    process.exit(1)
  }

  return {
    supabaseUrl,
    serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
    keepSuperAdminEmail: process.env.KEEP_SUPER_ADMIN_EMAIL || 'admin@wisper.com',
  }
}

/**
 * Mask sensitive connection string for logging
 * @param {string} url - Database URL
 * @returns {string} Masked URL
 */
export function maskConnectionString(url) {
  if (!url) return '[not set]'

  try {
    const urlObj = new URL(url)
    if (urlObj.password) {
      urlObj.password = '***'
    }
    return urlObj.toString()
  } catch {
    return '[invalid URL]'
  }
}

/**
 * Mask API key for logging
 * @param {string} key - API key
 * @returns {string} Masked key
 */
export function maskApiKey(key) {
  if (!key) return '[not set]'
  if (key.length < 20) return '***'

  return `${key.substring(0, 8)}...${key.substring(key.length - 8)}`
}
