-- UAT Reset Script
-- DELETES ALL QA DATA - USE WITH EXTREME CAUTION
-- Preserves ONLY one SUPER_ADMIN and system configuration
-- Author: Generated by Claude Code
-- Date: 2026-08-31

-- ============================================================================
-- CONFIGURATION
-- ============================================================================
-- Set this to the SUPER_ADMIN email you want to KEEP
\set KEEP_SUPER_ADMIN_EMAIL '''omar.ramirez@innocore.mx'''

-- ============================================================================
-- GUARD RAILS - Validate before proceeding
-- ============================================================================

DO $$
DECLARE
  v_keep_admin_count INTEGER;
  v_keep_admin_id UUID;
  v_keep_admin_email TEXT;
BEGIN
  -- Check that exactly ONE SUPER_ADMIN with the specified email exists
  SELECT COUNT(*), MAX(id), MAX(email)
  INTO v_keep_admin_count, v_keep_admin_id, v_keep_admin_email
  FROM profiles
  WHERE role = 'SUPER_ADMIN'
    AND LOWER(TRIM(email)) = LOWER(TRIM(:'KEEP_SUPER_ADMIN_EMAIL'));

  IF v_keep_admin_count = 0 THEN
    RAISE EXCEPTION 'ABORT: SUPER_ADMIN with email % not found', :'KEEP_SUPER_ADMIN_EMAIL';
  END IF;

  IF v_keep_admin_count > 1 THEN
    RAISE EXCEPTION 'ABORT: Multiple SUPER_ADMINs with email % found (count: %)', :'KEEP_SUPER_ADMIN_EMAIL', v_keep_admin_count;
  END IF;

  -- Verify auth.users record exists
  IF NOT EXISTS (
    SELECT 1 FROM auth.users WHERE id = v_keep_admin_id
  ) THEN
    RAISE EXCEPTION 'ABORT: SUPER_ADMIN profile exists but auth.users record missing (id: %)', v_keep_admin_id;
  END IF;

  RAISE NOTICE '✅ Validation passed: Found SUPER_ADMIN to keep';
  RAISE NOTICE '   ID: %', v_keep_admin_id;
  RAISE NOTICE '   Email: %', v_keep_admin_email;
END $$;

-- ============================================================================
-- RESET OPERATION - Delete in correct order respecting FKs
-- ============================================================================

BEGIN;

RAISE NOTICE '🚀 Starting UAT reset...';

-- ============================================================================
-- 1. DELETE TICKET-RELATED DATA (respecting FKs)
-- ============================================================================

RAISE NOTICE 'Deleting ticket activity...';
DELETE FROM ticket_activity;

RAISE NOTICE 'Deleting ticket status history...';
DELETE FROM ticket_status_history;

RAISE NOTICE 'Deleting ticket evidences...';
DELETE FROM ticket_evidences;

RAISE NOTICE 'Deleting ticket signatures...';
DELETE FROM ticket_signatures;

RAISE NOTICE 'Deleting tickets...';
DELETE FROM tickets;

-- Reset ticket folio sequence
RAISE NOTICE 'Resetting ticket folio sequence...';
ALTER SEQUENCE tickets_folio_seq RESTART WITH 1000;

-- ============================================================================
-- 2. DELETE TECHNICIAN DATA
-- ============================================================================

RAISE NOTICE 'Deleting technician push tokens...';
DELETE FROM technician_push_tokens;

RAISE NOTICE 'Deleting technician locations...';
DELETE FROM technician_locations;

RAISE NOTICE 'Deleting technicians...';
DELETE FROM technicians;

-- ============================================================================
-- 3. DELETE CLIENTS
-- ============================================================================

RAISE NOTICE 'Deleting clients...';
DELETE FROM clients;

-- ============================================================================
-- 4. DELETE AUTH.USERS (except SUPER_ADMIN to keep)
-- ============================================================================

-- IMPORTANT: auth.users → profiles CASCADE relationship
-- profiles.id REFERENCES auth.users(id) ON DELETE CASCADE
-- Deleting auth.users will CASCADE delete profiles automatically
-- This also CASCADE deletes technicians (profile_id references profiles)

RAISE NOTICE 'Deleting auth.users (except designated SUPER_ADMIN)...';
RAISE NOTICE 'This will CASCADE delete profiles and technicians...';

DELETE FROM auth.users
WHERE id NOT IN (
  SELECT id FROM profiles
  WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:'KEEP_SUPER_ADMIN_EMAIL'))
);

-- ============================================================================
-- 6. CLEAN STORAGE BUCKETS
-- ============================================================================

-- IMPORTANT: Do NOT delete storage.objects directly here
-- Use scripts/uat-reset-storage.mjs instead
-- Storage cleanup must use Supabase Storage API .remove()
-- Direct DELETE can leave orphaned physical files

RAISE NOTICE 'Storage cleanup skipped - use uat-reset-storage.mjs';

-- ============================================================================
-- FINAL VERIFICATION
-- ============================================================================

RAISE NOTICE '🔍 Verifying reset...';

-- Verify exactly 1 profile remains (SUPER_ADMIN)
IF (SELECT COUNT(*) FROM profiles) != 1 THEN
  RAISE EXCEPTION 'Verification failed: Expected 1 profile, found %',
    (SELECT COUNT(*) FROM profiles);
END IF;

-- Verify exactly 1 SUPER_ADMIN
IF (SELECT COUNT(*) FROM profiles WHERE role = 'SUPER_ADMIN') != 1 THEN
  RAISE EXCEPTION 'Verification failed: Expected 1 SUPER_ADMIN, found %',
    (SELECT COUNT(*) FROM profiles WHERE role = 'SUPER_ADMIN');
END IF;

-- Verify exactly 1 auth.users
IF (SELECT COUNT(*) FROM auth.users) != 1 THEN
  RAISE EXCEPTION 'Verification failed: Expected 1 auth.users, found %',
    (SELECT COUNT(*) FROM auth.users);
END IF;

-- Verify transactional tables are empty
IF (SELECT COUNT(*) FROM tickets) != 0 THEN
  RAISE EXCEPTION 'Verification failed: tickets table not empty (count: %)',
    (SELECT COUNT(*) FROM tickets);
END IF;

IF (SELECT COUNT(*) FROM ticket_activity) != 0 THEN
  RAISE EXCEPTION 'Verification failed: ticket_activity table not empty (count: %)',
    (SELECT COUNT(*) FROM ticket_activity);
END IF;

IF (SELECT COUNT(*) FROM ticket_evidences) != 0 THEN
  RAISE EXCEPTION 'Verification failed: ticket_evidences table not empty (count: %)',
    (SELECT COUNT(*) FROM ticket_evidences);
END IF;

IF (SELECT COUNT(*) FROM technicians) != 0 THEN
  RAISE EXCEPTION 'Verification failed: technicians table not empty (count: %)',
    (SELECT COUNT(*) FROM technicians);
END IF;

IF (SELECT COUNT(*) FROM clients) != 0 THEN
  RAISE EXCEPTION 'Verification failed: clients table not empty (count: %)',
    (SELECT COUNT(*) FROM clients);
END IF;

RAISE NOTICE '✅ UAT Reset completed successfully';
RAISE NOTICE 'Remaining SUPER_ADMIN: %', :'KEEP_SUPER_ADMIN_EMAIL';

COMMIT;

-- ============================================================================
-- POST-RESET SUMMARY
-- ============================================================================

SELECT
  'profiles' as table_name,
  COUNT(*) as remaining_rows
FROM profiles
UNION ALL
SELECT 'auth.users', COUNT(*) FROM auth.users
UNION ALL
SELECT 'technicians', COUNT(*) FROM technicians
UNION ALL
SELECT 'clients', COUNT(*) FROM clients
UNION ALL
SELECT 'tickets', COUNT(*) FROM tickets
UNION ALL
SELECT 'ticket_activity', COUNT(*) FROM ticket_activity
UNION ALL
SELECT 'ticket_status_history', COUNT(*) FROM ticket_status_history
UNION ALL
SELECT 'ticket_evidences', COUNT(*) FROM ticket_evidences
UNION ALL
SELECT 'ticket_signatures', COUNT(*) FROM ticket_signatures
UNION ALL
SELECT 'technician_locations', COUNT(*) FROM technician_locations
UNION ALL
SELECT 'technician_push_tokens', COUNT(*) FROM technician_push_tokens
UNION ALL
SELECT 'storage.objects (evidences)', COUNT(*)
  FROM storage.objects WHERE bucket_id = 'ticket-evidences'
UNION ALL
SELECT 'storage.objects (signatures)', COUNT(*)
  FROM storage.objects WHERE bucket_id = 'ticket-signatures';
