-- UAT Reset Preview Script
-- Shows what WOULD be deleted without actually deleting anything
-- Run this BEFORE uat-reset.sql to review the impact
-- Author: Generated by Claude Code
-- Date: 2026-08-31

-- ============================================================================
-- CONFIGURATION
-- ============================================================================
-- Set this to the SUPER_ADMIN email you want to KEEP
-- All other users will be marked for deletion

\set KEEP_SUPER_ADMIN_EMAIL '''admin@wisper.com'''

-- ============================================================================
-- SUPER_ADMIN USERS
-- ============================================================================

SELECT '=== SUPER_ADMIN USERS (CURRENT) ===' as section;

SELECT
  p.id as profile_id,
  p.full_name,
  p.email,
  p.role,
  p.is_active,
  au.id as auth_user_id,
  au.email as auth_email,
  au.email_confirmed_at IS NOT NULL as email_confirmed,
  CASE
    WHEN LOWER(TRIM(p.email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL)) THEN '✅ KEEP'
    ELSE '❌ DELETE'
  END as action
FROM profiles p
JOIN auth.users au ON au.id = p.id
WHERE p.role = 'SUPER_ADMIN'
ORDER BY p.created_at;

-- ============================================================================
-- TABLE ROW COUNTS
-- ============================================================================

SELECT '=== CURRENT DATABASE STATE ===' as section;

SELECT
  'profiles' as table_name,
  COUNT(*) as total_rows,
  COUNT(*) FILTER (WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) != LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))) as super_admins_to_delete,
  COUNT(*) FILTER (WHERE role = 'ADMIN') as admins_to_delete,
  COUNT(*) FILTER (WHERE role = 'TECHNICIAN') as technicians_to_delete,
  COUNT(*) FILTER (WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))) as rows_to_keep
FROM profiles
UNION ALL
SELECT
  'technicians' as table_name,
  COUNT(*) as total_rows,
  0 as super_admins_to_delete,
  0 as admins_to_delete,
  COUNT(*) as technicians_to_delete,
  0 as rows_to_keep
FROM technicians
UNION ALL
SELECT
  'clients' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0 as rows_to_keep
FROM clients
UNION ALL
SELECT
  'tickets' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM tickets
UNION ALL
SELECT
  'ticket_activity' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM ticket_activity
UNION ALL
SELECT
  'ticket_status_history' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM ticket_status_history
UNION ALL
SELECT
  'ticket_evidences' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM ticket_evidences
UNION ALL
SELECT
  'ticket_signatures' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM ticket_signatures
UNION ALL
SELECT
  'technician_locations' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM technician_locations
UNION ALL
SELECT
  'technician_push_tokens' as table_name,
  COUNT(*) as total_rows,
  0, 0,
  COUNT(*) as to_delete,
  0
FROM technician_push_tokens;

-- ============================================================================
-- AUTH.USERS TO DELETE
-- ============================================================================

SELECT '=== AUTH.USERS TO DELETE ===' as section;

SELECT
  au.id as auth_user_id,
  au.email as auth_email,
  p.email as profile_email,
  p.role,
  au.email_confirmed_at IS NOT NULL as email_confirmed,
  au.created_at,
  CASE
    WHEN LOWER(TRIM(p.email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL)) THEN '✅ KEEP'
    ELSE '❌ DELETE'
  END as action
FROM auth.users au
LEFT JOIN profiles p ON p.id = au.id
WHERE p.id IS NOT NULL  -- Only show users with profiles
ORDER BY au.created_at;

-- ============================================================================
-- STORAGE OBJECTS TO DELETE
-- ============================================================================

SELECT '=== STORAGE OBJECTS (EVIDENCES) ===' as section;

SELECT
  bucket_id,
  COUNT(*) as object_count,
  SUM((metadata->>'size')::bigint) as total_bytes,
  ROUND(SUM((metadata->>'size')::bigint) / 1024.0 / 1024.0, 2) as total_mb
FROM storage.objects
WHERE bucket_id = 'ticket-evidences'
GROUP BY bucket_id;

SELECT '=== STORAGE OBJECTS (SIGNATURES) ===' as section;

SELECT
  bucket_id,
  COUNT(*) as object_count,
  SUM((metadata->>'size')::bigint) as total_bytes,
  ROUND(SUM((metadata->>'size')::bigint) / 1024.0 / 1024.0, 2) as total_mb
FROM storage.objects
WHERE bucket_id = 'ticket-signatures'
GROUP BY bucket_id;

-- ============================================================================
-- SUMMARY
-- ============================================================================

SELECT '=== RESET SUMMARY ===' as section;

SELECT
  'SUPER_ADMIN to keep' as item,
  COUNT(*) as count
FROM profiles
WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))
UNION ALL
SELECT
  'Profiles to delete' as item,
  COUNT(*) as count
FROM profiles
WHERE NOT (role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL)))
UNION ALL
SELECT
  'Auth users to delete' as item,
  COUNT(*) as count
FROM auth.users au
JOIN profiles p ON p.id = au.id
WHERE NOT (p.role = 'SUPER_ADMIN' AND LOWER(TRIM(p.email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL)))
UNION ALL
SELECT
  'Tickets to delete' as item,
  COUNT(*) as count
FROM tickets
UNION ALL
SELECT
  'Storage evidence objects' as item,
  COUNT(*) as count
FROM storage.objects
WHERE bucket_id = 'ticket-evidences'
UNION ALL
SELECT
  'Storage signature objects' as item,
  COUNT(*) as count
FROM storage.objects
WHERE bucket_id = 'ticket-signatures';

-- ============================================================================
-- WARNINGS
-- ============================================================================

SELECT '=== WARNINGS ===' as section;

SELECT
  CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM profiles
      WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))
    ) THEN '🔴 ERROR: SUPER_ADMIN with email ' || :KEEP_SUPER_ADMIN_EMAIL || ' NOT FOUND'
    WHEN (SELECT COUNT(*) FROM profiles WHERE role = 'SUPER_ADMIN' AND LOWER(TRIM(email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))) > 1
    THEN '🔴 ERROR: Multiple SUPER_ADMINs with same email found'
    WHEN NOT EXISTS (
      SELECT 1 FROM auth.users au
      JOIN profiles p ON p.id = au.id
      WHERE p.role = 'SUPER_ADMIN' AND LOWER(TRIM(p.email)) = LOWER(TRIM(:KEEP_SUPER_ADMIN_EMAIL))
    ) THEN '🔴 ERROR: SUPER_ADMIN profile exists but auth.users record missing'
    ELSE '✅ SUPER_ADMIN validation passed'
  END as validation;
