-- UAT Reset Verification Script
-- Run this AFTER uat-reset.sql to verify the reset was successful
-- Author: Generated by Claude Code
-- Date: 2026-08-31

-- ============================================================================
-- VERIFICATION CHECKS
-- ============================================================================

SELECT '=== UAT RESET VERIFICATION ===' as section;

-- ============================================================================
-- 1. USER COUNTS
-- ============================================================================

SELECT '=== USER COUNTS ===' as section;

SELECT
  'SUPER_ADMIN count' as check_item,
  COUNT(*) as actual,
  1 as expected,
  CASE WHEN COUNT(*) = 1 THEN '✅ PASS' ELSE '❌ FAIL' END as status
FROM profiles
WHERE role = 'SUPER_ADMIN'
UNION ALL
SELECT
  'ADMIN count',
  COUNT(*),
  0 as expected,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM profiles
WHERE role = 'ADMIN'
UNION ALL
SELECT
  'TECHNICIAN profiles count',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM profiles
WHERE role = 'TECHNICIAN'
UNION ALL
SELECT
  'auth.users count',
  COUNT(*),
  1,
  CASE WHEN COUNT(*) = 1 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM auth.users;

-- ============================================================================
-- 2. TRANSACTIONAL DATA COUNTS
-- ============================================================================

SELECT '=== TRANSACTIONAL DATA ===' as section;

SELECT
  'tickets' as table_name,
  COUNT(*) as actual,
  0 as expected,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END as status
FROM tickets
UNION ALL
SELECT
  'ticket_activity',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM ticket_activity
UNION ALL
SELECT
  'ticket_status_history',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM ticket_status_history
UNION ALL
SELECT
  'ticket_evidences',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM ticket_evidences
UNION ALL
SELECT
  'ticket_signatures',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM ticket_signatures
UNION ALL
SELECT
  'technicians',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM technicians
UNION ALL
SELECT
  'technician_locations',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM technician_locations
UNION ALL
SELECT
  'technician_push_tokens',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM technician_push_tokens
UNION ALL
SELECT
  'clients',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM clients;

-- ============================================================================
-- 3. STORAGE OBJECTS
-- ============================================================================

SELECT '=== STORAGE BUCKETS ===' as section;

SELECT
  'ticket-evidences objects' as bucket,
  COUNT(*) as actual,
  0 as expected,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END as status
FROM storage.objects
WHERE bucket_id = 'ticket-evidences'
UNION ALL
SELECT
  'ticket-signatures objects',
  COUNT(*),
  0,
  CASE WHEN COUNT(*) = 0 THEN '✅ PASS' ELSE '❌ FAIL' END
FROM storage.objects
WHERE bucket_id = 'ticket-signatures';

-- ============================================================================
-- 4. SUPER_ADMIN PROFILE DETAILS
-- ============================================================================

SELECT '=== REMAINING SUPER_ADMIN ===' as section;

SELECT
  p.id as profile_id,
  p.full_name,
  p.email as profile_email,
  p.role,
  p.is_active,
  au.id as auth_user_id,
  au.email as auth_email,
  au.email_confirmed_at IS NOT NULL as email_confirmed,
  p.created_at as profile_created_at,
  au.created_at as auth_created_at
FROM profiles p
JOIN auth.users au ON au.id = p.id
WHERE p.role = 'SUPER_ADMIN';

-- ============================================================================
-- 5. CONFIGURATION PRESERVED
-- ============================================================================

SELECT '=== CONFIGURATION CHECK ===' as section;

SELECT
  'user_role enum' as config_item,
  CASE WHEN EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'user_role'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END as status
UNION ALL
SELECT
  'ticket_status enum',
  CASE WHEN EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'ticket_status'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END
UNION ALL
SELECT
  'ticket_activity_type enum',
  CASE WHEN EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'ticket_activity_type'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END
UNION ALL
SELECT
  'Storage bucket: ticket-evidences',
  CASE WHEN EXISTS (
    SELECT 1 FROM storage.buckets WHERE id = 'ticket-evidences'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END
UNION ALL
SELECT
  'Storage bucket: ticket-signatures',
  CASE WHEN EXISTS (
    SELECT 1 FROM storage.buckets WHERE id = 'ticket-signatures'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END
UNION ALL
SELECT
  'auth.users record for SUPER_ADMIN',
  CASE WHEN EXISTS (
    SELECT 1 FROM auth.users au
    JOIN profiles p ON p.id = au.id
    WHERE p.role = 'SUPER_ADMIN'
  ) THEN '✅ EXISTS' ELSE '❌ MISSING' END;

-- ============================================================================
-- 6. SEQUENCE STATUS
-- ============================================================================

SELECT '=== SEQUENCES ===' as section;

SELECT
  'tickets_folio_seq' as sequence_name,
  last_value as current_value,
  1000 as expected_start
FROM tickets_folio_seq;

-- ============================================================================
-- FINAL SUMMARY
-- ============================================================================

SELECT '=== VERIFICATION SUMMARY ===' as section;

SELECT
  CASE
    WHEN (SELECT COUNT(*) FROM profiles) = 1
      AND (SELECT COUNT(*) FROM profiles WHERE role = 'SUPER_ADMIN') = 1
      AND (SELECT COUNT(*) FROM auth.users) = 1
      AND (SELECT COUNT(*) FROM tickets) = 0
      AND (SELECT COUNT(*) FROM ticket_activity) = 0
      AND (SELECT COUNT(*) FROM ticket_status_history) = 0
      AND (SELECT COUNT(*) FROM ticket_evidences) = 0
      AND (SELECT COUNT(*) FROM ticket_signatures) = 0
      AND (SELECT COUNT(*) FROM technicians) = 0
      AND (SELECT COUNT(*) FROM clients) = 0
      AND (SELECT COUNT(*) FROM technician_push_tokens) = 0
      AND (SELECT COUNT(*) FROM technician_locations) = 0
      AND (SELECT COUNT(*) FROM storage.objects WHERE bucket_id IN ('ticket-evidences', 'ticket-signatures')) = 0
    THEN '✅ ALL DB CHECKS PASSED'
    ELSE '❌ SOME CHECKS FAILED - REVIEW REQUIRED'
  END as overall_status;

-- ============================================================================
-- MANUAL VALIDATION REQUIRED
-- ============================================================================

SELECT '=== MANUAL VALIDATION CHECKLIST ===' as section;

SELECT
  '1. Login to Admin Web with SUPER_ADMIN credentials' as step,
  'NOT VERIFIED BY SQL' as status
UNION ALL
SELECT
  '2. Verify authentication succeeds',
  'NOT VERIFIED BY SQL'
UNION ALL
SELECT
  '3. Verify admin can create new users',
  'NOT VERIFIED BY SQL'
UNION ALL
SELECT
  '4. Verify admin can create clients',
  'NOT VERIFIED BY SQL'
UNION ALL
SELECT
  '5. Verify admin can create tickets',
  'NOT VERIFIED BY SQL';
