#!/usr/bin/env node

/**
 * UAT Reset Script
 * DELETES ALL QA DATA - USE WITH EXTREME CAUTION
 * Preserves ONLY one SUPER_ADMIN and system configuration
 *
 * ⚠️  TRANSACTION LIMITATION:
 * Supabase JS does not support multi-table transactions like PostgreSQL.
 * This script uses strong guard rails and verification steps but cannot
 * guarantee atomic rollback if a mid-delete operation fails.
 *
 * Author: Generated by Claude Code
 * Date: 2026-08-31
 */

import { createClient } from '@supabase/supabase-js'
import { loadEnv, validateEnv } from './lib/load-env.mjs'

// Load environment variables
loadEnv()

// Validate required variables
const config = validateEnv()

// ============================================================================
// CONFIGURATION
// ============================================================================

const KEEP_SUPER_ADMIN_EMAIL = config.keepSuperAdminEmail
const UAT_RESET_CONFIRMED = process.env.UAT_RESET_CONFIRMED

if (UAT_RESET_CONFIRMED !== 'yes') {
  console.error('❌ ERROR: UAT_RESET_CONFIRMED not set to "yes"')
  console.error('')
  console.error('This script will DELETE ALL UAT DATA.')
  console.error('To confirm, run:')
  console.error('  UAT_RESET_CONFIRMED=yes npm run uat:reset')
  console.error('')
  process.exit(1)
}

// Create Supabase admin client (server-side only)
const supabase = createClient(config.supabaseUrl, config.serviceRoleKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
})

// ============================================================================
// DELETE HELPERS
// ============================================================================

/**
 * Delete all rows from a table
 * Uses appropriate strategy based on PK type
 * @param {string} tableName - Table to delete from
 * @param {string} pkType - 'uuid' or 'bigint'
 * @returns {Promise<{deleted: number, error: any}>}
 */
async function deleteAll(tableName, pkType = 'uuid') {
  try {
    // Check current count first
    const { count: beforeCount, error: countError } = await supabase
      .from(tableName)
      .select('*', { count: 'exact', head: true })

    if (countError) {
      return { deleted: 0, error: countError }
    }

    if (beforeCount === 0) {
      console.log(`  already empty`)
      return { deleted: 0, error: null }
    }

    // Delete based on PK type
    let deleteQuery
    if (pkType === 'bigint') {
      // For bigint PKs: use >= 0 (all positive IDs)
      deleteQuery = supabase.from(tableName).delete().gte('id', 0)
    } else {
      // For uuid PKs: use NOT NULL condition
      deleteQuery = supabase.from(tableName).delete().not('id', 'is', null)
    }

    const { error: deleteError, count: deletedCount } = await deleteQuery

    if (deleteError) {
      return { deleted: 0, error: deleteError }
    }

    // Verify deletion
    const { count: afterCount } = await supabase
      .from(tableName)
      .select('*', { count: 'exact', head: true })

    console.log(`  deleted: ${beforeCount}`)
    console.log(`  remaining: ${afterCount || 0}`)
    console.log(`  ✅ PASS`)

    return { deleted: beforeCount, error: null }
  } catch (err) {
    return { deleted: 0, error: err }
  }
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
  try {
    console.log('='.repeat(80))
    console.log('🔥 WISPER UAT RESET — EXECUTE')
    console.log('='.repeat(80))
    console.log('')
    console.log('⚠️  WARNING: This will DELETE ALL UAT DATA')
    console.log('⚠️  NOTE: No atomic transaction - operations are sequential')
    console.log('')

    // ========================================================================
    // 1. GUARD RAILS - Validate before proceeding
    // ========================================================================

    console.log('🔍 Running pre-flight validation...')
    console.log('')

    const { data: superAdmins, error: superAdminError } = await supabase
      .from('profiles')
      .select('id, email, full_name, role')
      .eq('role', 'SUPER_ADMIN')
      .ilike('email', KEEP_SUPER_ADMIN_EMAIL.trim())

    if (superAdminError) {
      throw new Error(`Failed to query profiles: ${superAdminError.message}`)
    }

    if (!superAdmins || superAdmins.length === 0) {
      throw new Error(`SUPER_ADMIN with email ${KEEP_SUPER_ADMIN_EMAIL} not found`)
    }

    if (superAdmins.length > 1) {
      throw new Error(`Multiple SUPER_ADMINs with email ${KEEP_SUPER_ADMIN_EMAIL} found`)
    }

    const keepAdmin = superAdmins[0]

    // Verify auth user exists
    const { data: authUser, error: authError } = await supabase.auth.admin.getUserById(keepAdmin.id)

    if (authError || !authUser) {
      throw new Error('SUPER_ADMIN profile exists but auth user not found')
    }

    console.log('✅ Validation passed')
    console.log('   SUPER_ADMIN to keep:')
    console.log('   Profile ID:', keepAdmin.id)
    console.log('   Auth ID:', authUser.user.id)
    console.log('   Email:', keepAdmin.email)
    console.log('   Name:', keepAdmin.full_name)
    console.log('')

    // ========================================================================
    // 2. DELETE TICKET-RELATED DATA (respecting FKs)
    // ========================================================================

    console.log('🚀 Starting UAT reset...')
    console.log('')

    // ========================================================================
    // 2. DELETE TICKET-RELATED DATA (respecting FKs)
    // ========================================================================

    console.log('Deleting ticket activity...')
    const activityResult = await deleteAll('ticket_activity', 'uuid')
    if (activityResult.error) throw new Error(`Failed to delete ticket_activity: ${activityResult.error.message}`)

    console.log('Deleting ticket status history...')
    const historyResult = await deleteAll('ticket_status_history', 'uuid')
    if (historyResult.error) throw new Error(`Failed to delete ticket_status_history: ${historyResult.error.message}`)

    console.log('Deleting ticket evidences...')
    const evidencesResult = await deleteAll('ticket_evidences', 'uuid')
    if (evidencesResult.error) throw new Error(`Failed to delete ticket_evidences: ${evidencesResult.error.message}`)

    console.log('Deleting ticket signatures...')
    const signaturesResult = await deleteAll('ticket_signatures', 'uuid')
    if (signaturesResult.error) throw new Error(`Failed to delete ticket_signatures: ${signaturesResult.error.message}`)

    console.log('Deleting tickets...')
    const ticketsResult = await deleteAll('tickets', 'uuid')
    if (ticketsResult.error) throw new Error(`Failed to delete tickets: ${ticketsResult.error.message}`)

    console.log('')

    // ========================================================================
    // 3. DELETE TECHNICIAN DATA
    // ========================================================================

    console.log('Deleting technician push tokens...')
    const tokensResult = await deleteAll('technician_push_tokens', 'uuid')
    if (tokensResult.error) throw new Error(`Failed to delete technician_push_tokens: ${tokensResult.error.message}`)

    console.log('Deleting technician locations...')
    const locationsResult = await deleteAll('technician_locations', 'bigint')
    if (locationsResult.error) throw new Error(`Failed to delete technician_locations: ${locationsResult.error.message}`)

    console.log('')

    // ========================================================================
    // 4. DELETE CLIENTS
    // ========================================================================

    console.log('Deleting clients...')
    const clientsResult = await deleteAll('clients', 'uuid')
    if (clientsResult.error) throw new Error(`Failed to delete clients: ${clientsResult.error.message}`)

    console.log('')

    // ========================================================================
    // 5. DELETE AUTH.USERS (CASCADE to profiles and technicians)
    // ========================================================================

    console.log('Deleting auth users (except designated SUPER_ADMIN)...')
    console.log('This will CASCADE delete profiles and technicians...')

    const { data: allAuthUsers, error: listError } = await supabase.auth.admin.listUsers()

    if (listError) {
      throw new Error(`Failed to list auth users: ${listError.message}`)
    }

    const usersToDelete = allAuthUsers.users.filter(u => u.id !== keepAdmin.id)

    console.log(`Found ${usersToDelete.length} auth users to delete...`)

    for (const user of usersToDelete) {
      const { error: deleteError } = await supabase.auth.admin.deleteUser(user.id)
      if (deleteError) {
        console.error(`⚠️  Failed to delete user ${user.id}: ${deleteError.message}`)
        // Continue with other users
      }
    }

    console.log('')

    // ========================================================================
    // 6. VERIFICATION
    // ========================================================================

    console.log('🔍 Verifying reset...')
    console.log('')

    const { count: profilesCount } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true })

    const { count: superAdminsCount } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true })
      .eq('role', 'SUPER_ADMIN')

    const { count: ticketsCount } = await supabase
      .from('tickets')
      .select('*', { count: 'exact', head: true })

    const { count: activitiesCount } = await supabase
      .from('ticket_activity')
      .select('*', { count: 'exact', head: true })

    const { count: evidencesCount } = await supabase
      .from('ticket_evidences')
      .select('*', { count: 'exact', head: true })

    const { count: techniciansCount } = await supabase
      .from('technicians')
      .select('*', { count: 'exact', head: true })

    const { count: clientsCount } = await supabase
      .from('clients')
      .select('*', { count: 'exact', head: true })

    const { data: authUsersRemaining } = await supabase.auth.admin.listUsers()

    const errors = []

    if (profilesCount !== 1) {
      errors.push(`Expected 1 profile, found ${profilesCount}`)
    }

    if (superAdminsCount !== 1) {
      errors.push(`Expected 1 SUPER_ADMIN, found ${superAdminsCount}`)
    }

    if (authUsersRemaining.users.length !== 1) {
      errors.push(`Expected 1 auth.users, found ${authUsersRemaining.users.length}`)
    }

    if (ticketsCount !== 0) {
      errors.push(`tickets table not empty (count: ${ticketsCount})`)
    }

    if (activitiesCount !== 0) {
      errors.push(`ticket_activity table not empty (count: ${activitiesCount})`)
    }

    if (evidencesCount !== 0) {
      errors.push(`ticket_evidences table not empty (count: ${evidencesCount})`)
    }

    if (techniciansCount !== 0) {
      errors.push(`technicians table not empty (count: ${techniciansCount})`)
    }

    if (clientsCount !== 0) {
      errors.push(`clients table not empty (count: ${clientsCount})`)
    }

    if (errors.length > 0) {
      console.log('❌ Verification failed:')
      errors.forEach(err => console.log('   -', err))
      console.log('')
      console.log('⚠️  Some data may remain due to FK constraints or deletion failures')
      console.log('⚠️  Manual cleanup may be required')
      process.exit(1)
    }

    console.log('✅ Verification passed')
    console.log('')

    console.log('='.repeat(80))
    console.log('✅ UAT DATABASE RESET COMPLETE')
    console.log('='.repeat(80))
    console.log('')
    console.log('Remaining SUPER_ADMIN:', keepAdmin.email)
    console.log('')
    console.log('⚠️  Storage objects NOT deleted yet')
    console.log('')
    console.log('Next steps:')
    console.log('  1. UAT_RESET_CONFIRMED=yes npm run uat:storage:reset')
    console.log('  2. npm run uat:verify')
    console.log('')
  } catch (error) {
    console.error('❌ Error:', error.message)
    console.log('')
    console.log('⚠️  Reset failed - some data may have been deleted')
    console.log('⚠️  Run npm run uat:verify to check current state')
    process.exit(1)
  }
}

main()
