-- Fix Storage RLS policies for ticket-signatures to allow technician uploads
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-MOBILE-SIGNATURE-HF02

-- ============================================================================
-- PROBLEM IDENTIFIED
-- ============================================================================
--
-- Current INSERT policy only checks if user is a technician, but doesn't
-- validate that the technician has access to the specific ticket.
--
-- Path format: {ticket_id}/signature-{timestamp}-{random}.png
--
-- We need to extract ticket_id from the path and validate that:
-- 1. The ticket exists
-- 2. The ticket is assigned to the current technician
--
-- ============================================================================

-- Drop existing overly permissive INSERT policy
DROP POLICY IF EXISTS "Technicians can upload signatures" ON storage.objects;

-- Create new INSERT policy that validates ticket ownership
CREATE POLICY "Technicians can upload signatures for their tickets"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM tickets
    WHERE tickets.id::text = split_part(storage.objects.name, '/', 1)
      AND tickets.technician_id = current_technician_id()
  )
);

-- Drop existing UPDATE policy that depends on ticket_signatures record existing
DROP POLICY IF EXISTS "Technicians can update signatures" ON storage.objects;

-- Create new UPDATE policy that validates ticket ownership from path
-- (Note: upsert now disabled in code, but keeping UPDATE for manual operations)
CREATE POLICY "Technicians can update their ticket signatures"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM tickets
    WHERE tickets.id::text = split_part(storage.objects.name, '/', 1)
      AND tickets.technician_id = current_technician_id()
      AND tickets.status != 'RESOLVED'
  )
);

-- Ensure SELECT policy allows technicians to read their signatures
-- (Existing policy "Admins and technicians can read signatures" is too permissive)
DROP POLICY IF EXISTS "Admins and technicians can read signatures" ON storage.objects;

-- Admins can read all signatures
CREATE POLICY "Admins can read all signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN')
);

-- Technicians can ONLY read signatures for their own tickets
CREATE POLICY "Technicians can read their ticket signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM tickets
    WHERE tickets.id::text = split_part(storage.objects.name, '/', 1)
      AND tickets.technician_id = current_technician_id()
  )
);
