-- Backfill evidence_id and signature_id for existing ticket_activity records
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-ADMIN-ACTIVITY-MEDIA-02

-- ============================================================================
-- PROBLEM
-- ============================================================================
--
-- Events created BEFORE the ticket_activity migration don't have evidence_id
-- or signature_id populated, even though the evidences/signatures exist.
--
-- This backfill script updates existing EVIDENCE_ADDED and SIGNATURE_ADDED
-- events to link them with their corresponding files.
--
-- ============================================================================

-- Backfill evidence_id for EVIDENCE_ADDED events
-- Match by ticket_id and approximate timestamp (within 5 seconds)
UPDATE ticket_activity
SET evidence_id = (
  SELECT te.id
  FROM ticket_evidences te
  WHERE te.ticket_id = ticket_activity.ticket_id
    AND te.created_at >= ticket_activity.created_at - interval '5 seconds'
    AND te.created_at <= ticket_activity.created_at + interval '5 seconds'
  ORDER BY ABS(EXTRACT(EPOCH FROM (te.created_at - ticket_activity.created_at)))
  LIMIT 1
)
WHERE ticket_activity.activity_type = 'EVIDENCE_ADDED'
  AND ticket_activity.evidence_id IS NULL;

-- Backfill signature_id for SIGNATURE_ADDED events
-- Match by ticket_id (usually only one signature per ticket)
UPDATE ticket_activity
SET signature_id = (
  SELECT ts.id
  FROM ticket_signatures ts
  WHERE ts.ticket_id = ticket_activity.ticket_id
    AND ts.signed_at >= ticket_activity.created_at - interval '30 seconds'
    AND ts.signed_at <= ticket_activity.created_at + interval '30 seconds'
  ORDER BY ABS(EXTRACT(EPOCH FROM (ts.signed_at - ticket_activity.created_at)))
  LIMIT 1
)
WHERE ticket_activity.activity_type = 'SIGNATURE_ADDED'
  AND ticket_activity.signature_id IS NULL;

-- Log backfill results
DO $$
DECLARE
  evidence_count INTEGER;
  signature_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO evidence_count
  FROM ticket_activity
  WHERE activity_type = 'EVIDENCE_ADDED' AND evidence_id IS NOT NULL;

  SELECT COUNT(*) INTO signature_count
  FROM ticket_activity
  WHERE activity_type = 'SIGNATURE_ADDED' AND signature_id IS NOT NULL;

  RAISE NOTICE 'Backfill complete:';
  RAISE NOTICE '  - % EVIDENCE_ADDED events now have evidence_id', evidence_count;
  RAISE NOTICE '  - % SIGNATURE_ADDED events now have signature_id', signature_count;
END $$;
