-- Add DELETE policy for ticket_evidences to allow technicians to delete their own evidences
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-MOBILE-HF12 - Evidences could not be deleted due to missing RLS DELETE policy

-- ============================================================================
-- ADD: DELETE policy for ticket_evidences
-- ============================================================================

-- Admins can delete any evidence
CREATE POLICY "Admins can delete evidences"
  ON ticket_evidences FOR DELETE
  USING (is_admin());

-- Technicians can delete evidences from their own tickets
-- Restriction: Cannot delete from RESOLVED tickets (preserve audit trail)
CREATE POLICY "Technicians can delete their ticket evidences"
  ON ticket_evidences FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_evidences.ticket_id
        AND tickets.technician_id = current_technician_id()
        AND tickets.status != 'RESOLVED'
    )
  );
