-- Add UPDATE policy for ticket_signatures to support upsert operations
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-MOBILE-SIGNATURE-HF02

-- ============================================================================
-- PROBLEM
-- ============================================================================
--
-- ticket_signatures table only had SELECT and INSERT policies for technicians.
-- The uploadSignature function uses .upsert() which requires UPDATE policy.
--
-- Without UPDATE policy, technicians cannot replace signatures.
--
-- ============================================================================

-- Allow admins to update signatures
CREATE POLICY "Admins can update signatures"
  ON ticket_signatures FOR UPDATE
  USING (is_admin());

-- Allow technicians to update signatures for their tickets (not RESOLVED)
CREATE POLICY "Technicians can update signatures for their tickets"
  ON ticket_signatures FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_signatures.ticket_id
        AND tickets.technician_id = current_technician_id()
        AND tickets.status != 'RESOLVED'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_signatures.ticket_id
        AND tickets.technician_id = current_technician_id()
        AND tickets.status != 'RESOLVED'
    )
  );
