-- Create view for latest location of each technician
-- Author: Generated by Claude Code
-- Date: 2026-08-15

CREATE OR REPLACE VIEW technician_latest_locations AS
SELECT DISTINCT ON (technician_id)
  technician_id,
  latitude,
  longitude,
  accuracy,
  recorded_at
FROM technician_locations
ORDER BY technician_id, recorded_at DESC;

-- Allow admin to query this view
GRANT SELECT ON technician_latest_locations TO authenticated;
