-- Fix Storage RLS policies to allow SUPER_ADMIN read access
-- Author: Generated by Claude Code
-- Date: 2026-08-30
-- Issue: WIS-STORAGE-HF08

-- ============================================================================
-- PROBLEM
-- ============================================================================
-- Current Storage policies only allow role = 'ADMIN' to read evidences/signatures
-- SUPER_ADMIN users cannot access Storage objects, causing "Object not found" errors
-- even though files physically exist
--
-- This migration adds SUPER_ADMIN to SELECT policies for:
-- - ticket-evidences bucket
-- - ticket-signatures bucket
--
-- Buckets remain PRIVATE. Technician policies remain unchanged.
-- ============================================================================

-- ============================================================================
-- FIX: ticket-evidences READ policy
-- ============================================================================

-- Drop existing policies (idempotent)
DROP POLICY IF EXISTS "Admins can read evidences" ON storage.objects;
DROP POLICY IF EXISTS "Admins and Super Admins can read evidences" ON storage.objects;

-- Create new policy allowing both ADMIN and SUPER_ADMIN
CREATE POLICY "Admins and Super Admins can read evidences"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-evidences' AND
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role IN ('ADMIN'::user_role, 'SUPER_ADMIN'::user_role)
  )
);

-- ============================================================================
-- FIX: ticket-signatures READ policy
-- ============================================================================

-- Drop existing policies (idempotent)
DROP POLICY IF EXISTS "Admins can read signatures" ON storage.objects;
DROP POLICY IF EXISTS "Admins can read all signatures" ON storage.objects;
DROP POLICY IF EXISTS "Admins and Super Admins can read signatures" ON storage.objects;

-- Create new policy allowing both ADMIN and SUPER_ADMIN
CREATE POLICY "Admins and Super Admins can read signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role IN ('ADMIN'::user_role, 'SUPER_ADMIN'::user_role)
  )
);

-- ============================================================================
-- VERIFICATION
-- ============================================================================
-- After migration, both ADMIN and SUPER_ADMIN should be able to:
-- - Create signed URLs for evidences
-- - Create signed URLs for signatures
-- - View thumbnails in Admin Web
--
-- Technician policies remain unchanged (scoped to their tickets)
-- Buckets remain PRIVATE (public = false)
-- ============================================================================
