-- Fix ticket_evidences RLS to work with PostgREST embeds from ticket_activity
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-EVIDENCE-E2E-HF01

-- ============================================================================
-- PROBLEM IDENTIFIED
-- ============================================================================
--
-- When Admin queries ticket_activity with PostgREST embed:
--   evidence:ticket_evidences!evidence_id(file_url)
--
-- PostgREST performs a LEFT JOIN, but RLS policies are evaluated AFTER the join.
-- The existing policy "Admins can view all evidences" uses is_admin() which checks
-- profiles table, but in some contexts the join may fail or the function may not
-- be evaluating correctly for Admin Web users.
--
-- Additionally, super admins need explicit access.
--
-- ============================================================================

-- Drop existing admin policy and recreate to include both ADMIN and SUPER_ADMIN
DROP POLICY IF EXISTS "Admins can view all evidences" ON ticket_evidences;

-- Admins and super admins can view all evidences
CREATE POLICY "Admins and super admins can view all evidences"
  ON ticket_evidences FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('ADMIN', 'SUPER_ADMIN')
    )
  );

-- Technicians policy remains unchanged (already exists)
-- "Technicians can view evidences for their tickets"

-- ============================================================================
-- FIX TICKET_SIGNATURES AS WELL (Same Issue)
-- ============================================================================

-- ticket_signatures has the same RLS issue
-- Drop and recreate with SUPER_ADMIN support

DROP POLICY IF EXISTS "Admins can view signatures" ON ticket_signatures;

CREATE POLICY "Admins and super admins can view signatures"
  ON ticket_signatures FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('ADMIN', 'SUPER_ADMIN')
    )
  );

-- Technician signature policies remain unchanged

-- ============================================================================
-- VERIFICATION
-- ============================================================================
-- After applying this migration:
--
-- 1. Admin users should see evidence thumbnails in ticket activity
-- 2. PostgREST embed should resolve: evidence:ticket_evidences!evidence_id(file_url)
-- 3. Debug output should show: has_evidence: true, evidence: { file_url: "..." }
--
-- Test with:
-- SELECT * FROM ticket_evidences WHERE id = 'd845bf64-1d75-48cb-b670-86725bb1cdc4';
--
-- As admin user via Supabase client (Auth header present)
-- ============================================================================
