-- Create ticket_activity table for comprehensive ticket event log
-- Author: Generated by Claude Code
-- Date: 2026-08-29
-- Issue: WIS-023-HF01 - Comprehensive ticket activity timeline

-- ============================================================================
-- ACTIVITY TYPE ENUM
-- ============================================================================

CREATE TYPE ticket_activity_type AS ENUM (
  'TICKET_CREATED',
  'TECHNICIAN_ASSIGNED',
  'TECHNICIAN_REASSIGNED',
  'TECHNICIAN_UNASSIGNED',
  'WORK_STARTED',
  'STATUS_CHANGED',
  'PAUSED',
  'RESUMED',
  'TECHNICIAN_NOTE_ADDED',
  'ADMIN_NOTE_ADDED',
  'EVIDENCE_ADDED',
  'EVIDENCE_DELETED',
  'SIGNATURE_ADDED',
  'CLOSED',
  'CANCELLED'
);

-- ============================================================================
-- TICKET ACTIVITY TABLE
-- ============================================================================

CREATE TABLE ticket_activity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  activity_type ticket_activity_type NOT NULL,

  -- Actor information
  actor_profile_id uuid REFERENCES profiles(id) ON DELETE SET NULL,

  -- Status change details (for STATUS_CHANGED, PAUSED, RESUMED, etc.)
  previous_status ticket_status,
  new_status ticket_status,

  -- General purpose note/message
  note text,

  -- Related entities
  evidence_id uuid REFERENCES ticket_evidences(id) ON DELETE SET NULL,
  signature_id uuid REFERENCES ticket_signatures(id) ON DELETE SET NULL,
  assigned_technician_id uuid REFERENCES technicians(id) ON DELETE SET NULL,
  previous_technician_id uuid REFERENCES technicians(id) ON DELETE SET NULL,

  -- Flexible metadata for future extensibility
  metadata jsonb,

  created_at timestamptz DEFAULT now() NOT NULL
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX idx_ticket_activity_ticket_id_created_at
  ON ticket_activity(ticket_id, created_at DESC);

CREATE INDEX idx_ticket_activity_type
  ON ticket_activity(activity_type);

CREATE INDEX idx_ticket_activity_actor
  ON ticket_activity(actor_profile_id);

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

ALTER TABLE ticket_activity ENABLE ROW LEVEL SECURITY;

-- Super admins and admins can view all activity
CREATE POLICY "Admins and super admins can view all activity"
  ON ticket_activity FOR SELECT
  USING (is_admin_or_super());

-- Technicians can view activity for their tickets
CREATE POLICY "Technicians can view their ticket activity"
  ON ticket_activity FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_activity.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- System can insert activity (triggers will use this)
-- Admins can insert activity
CREATE POLICY "Admins can insert activity"
  ON ticket_activity FOR INSERT
  WITH CHECK (is_admin_or_super());

-- Technicians can insert activity for their tickets
CREATE POLICY "Technicians can insert activity for their tickets"
  ON ticket_activity FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_activity.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- TRIGGERS - Auto-log ticket lifecycle events
-- ============================================================================

-- Log ticket creation
CREATE OR REPLACE FUNCTION log_ticket_created()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO ticket_activity (
    ticket_id,
    activity_type,
    actor_profile_id,
    new_status
  ) VALUES (
    NEW.id,
    'TICKET_CREATED',
    auth.uid(),
    NEW.status
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_ticket_created
  AFTER INSERT ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_ticket_created();

-- Log status changes (PAUSED, RESUMED, STATUS_CHANGED, CLOSED, CANCELLED)
CREATE OR REPLACE FUNCTION log_ticket_status_change_activity()
RETURNS TRIGGER AS $$
DECLARE
  activity_type_value ticket_activity_type;
BEGIN
  -- Only log if status actually changed
  IF OLD.status IS DISTINCT FROM NEW.status THEN

    -- Determine specific activity type based on status transition
    IF NEW.status = 'PAUSED' THEN
      activity_type_value := 'PAUSED';
    ELSIF OLD.status = 'PAUSED' AND NEW.status = 'IN_REVIEW' THEN
      activity_type_value := 'RESUMED';
    ELSIF NEW.status = 'IN_REVIEW' AND OLD.status IN ('ASSIGNED', 'PENDING') THEN
      activity_type_value := 'WORK_STARTED';
    ELSIF NEW.status = 'RESOLVED' THEN
      activity_type_value := 'CLOSED';
    ELSIF NEW.status = 'CANCELLED' THEN
      activity_type_value := 'CANCELLED';
    ELSE
      activity_type_value := 'STATUS_CHANGED';
    END IF;

    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      previous_status,
      new_status
    ) VALUES (
      NEW.id,
      activity_type_value,
      auth.uid(),
      OLD.status,
      NEW.status
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_ticket_status_change_activity
  AFTER UPDATE ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_ticket_status_change_activity();

-- Log technician assignments
CREATE OR REPLACE FUNCTION log_ticket_assignment()
RETURNS TRIGGER AS $$
BEGIN
  -- Assignment or reassignment
  IF OLD.technician_id IS NULL AND NEW.technician_id IS NOT NULL THEN
    -- Initial assignment
    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      assigned_technician_id
    ) VALUES (
      NEW.id,
      'TECHNICIAN_ASSIGNED',
      auth.uid(),
      NEW.technician_id
    );
  ELSIF OLD.technician_id IS NOT NULL AND NEW.technician_id IS NOT NULL AND OLD.technician_id != NEW.technician_id THEN
    -- Reassignment
    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      previous_technician_id,
      assigned_technician_id
    ) VALUES (
      NEW.id,
      'TECHNICIAN_REASSIGNED',
      auth.uid(),
      OLD.technician_id,
      NEW.technician_id
    );
  ELSIF OLD.technician_id IS NOT NULL AND NEW.technician_id IS NULL THEN
    -- Unassignment
    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      previous_technician_id
    ) VALUES (
      NEW.id,
      'TECHNICIAN_UNASSIGNED',
      auth.uid(),
      OLD.technician_id
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_ticket_assignment
  AFTER UPDATE OF technician_id ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_ticket_assignment();

-- Log evidence additions
CREATE OR REPLACE FUNCTION log_evidence_added()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO ticket_activity (
    ticket_id,
    activity_type,
    actor_profile_id,
    evidence_id
  ) VALUES (
    NEW.ticket_id,
    'EVIDENCE_ADDED',
    NEW.created_by,
    NEW.id
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_evidence_added
  AFTER INSERT ON ticket_evidences
  FOR EACH ROW
  EXECUTE FUNCTION log_evidence_added();

-- Log evidence deletions
CREATE OR REPLACE FUNCTION log_evidence_deleted()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO ticket_activity (
    ticket_id,
    activity_type,
    actor_profile_id,
    note,
    metadata
  ) VALUES (
    OLD.ticket_id,
    'EVIDENCE_DELETED',
    auth.uid(),
    'Evidencia eliminada',
    jsonb_build_object('file_url', OLD.file_url, 'evidence_id', OLD.id)
  );
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_evidence_deleted
  BEFORE DELETE ON ticket_evidences
  FOR EACH ROW
  EXECUTE FUNCTION log_evidence_deleted();

-- Log signature additions
CREATE OR REPLACE FUNCTION log_signature_added()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO ticket_activity (
    ticket_id,
    activity_type,
    actor_profile_id,
    signature_id,
    note
  ) VALUES (
    NEW.ticket_id,
    'SIGNATURE_ADDED',
    auth.uid(),
    NEW.id,
    'Firmado por: ' || COALESCE(NEW.signed_by_name, 'Cliente')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_signature_added
  AFTER INSERT ON ticket_signatures
  FOR EACH ROW
  EXECUTE FUNCTION log_signature_added();

-- Log technician notes changes
CREATE OR REPLACE FUNCTION log_technician_note_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Only log if technician_notes changed and is not null/empty
  IF OLD.technician_notes IS DISTINCT FROM NEW.technician_notes
     AND NEW.technician_notes IS NOT NULL
     AND trim(NEW.technician_notes) != '' THEN

    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      note
    ) VALUES (
      NEW.id,
      'TECHNICIAN_NOTE_ADDED',
      auth.uid(),
      NEW.technician_notes
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_technician_note_change
  AFTER UPDATE OF technician_notes ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_technician_note_change();

-- Log admin notes changes
CREATE OR REPLACE FUNCTION log_admin_note_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Only log if admin_notes changed and is not null/empty
  IF OLD.admin_notes IS DISTINCT FROM NEW.admin_notes
     AND NEW.admin_notes IS NOT NULL
     AND trim(NEW.admin_notes) != '' THEN

    INSERT INTO ticket_activity (
      ticket_id,
      activity_type,
      actor_profile_id,
      note
    ) VALUES (
      NEW.id,
      'ADMIN_NOTE_ADDED',
      auth.uid(),
      NEW.admin_notes
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_log_admin_note_change
  AFTER UPDATE OF admin_notes ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_admin_note_change();

-- ============================================================================
-- ENABLE REALTIME
-- ============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE ticket_activity;
