-- Auto-create profile when user signs up
-- Author: Generated by Claude Code
-- Date: 2026-08-14

-- ============================================================================
-- FUNCTION TO HANDLE NEW USER
-- ============================================================================

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_full_name text;
  user_phone text;
BEGIN
  -- Extract full_name from metadata, fallback to email username
  user_full_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    split_part(NEW.email, '@', 1)
  );

  -- Extract phone from metadata
  user_phone := NEW.raw_user_meta_data->>'phone';

  -- Create profile with TECHNICIAN role by default
  -- ADMIN role must be set manually via admin script
  INSERT INTO public.profiles (id, full_name, role, phone, is_active)
  VALUES (
    NEW.id,
    user_full_name,
    'TECHNICIAN'::user_role,
    user_phone,
    true
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- TRIGGER ON AUTH.USERS
-- ============================================================================

-- Drop trigger if exists (for idempotency)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Create trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();
