-- Create storage buckets and policies for evidences and signatures
-- Author: Generated by Claude Code
-- Date: 2026-08-15

-- Note: This migration assumes Supabase allows creating buckets via SQL
-- If your Supabase version doesn't support this, use the Dashboard or refer to STORAGE_SETUP.md

-- Create buckets (if not exist)
INSERT INTO storage.buckets (id, name, public)
VALUES
  ('ticket-evidences', 'ticket-evidences', false),
  ('ticket-signatures', 'ticket-signatures', false)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- STORAGE POLICIES - ticket-evidences
-- ============================================================================

-- Admins can upload
CREATE POLICY "Admins can upload evidences"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'ticket-evidences' AND
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN')
);

-- Technicians can upload evidences
CREATE POLICY "Technicians can upload evidences"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'ticket-evidences' AND
  EXISTS (SELECT 1 FROM technicians WHERE profile_id = auth.uid())
);

-- Admins and technicians can read evidences
CREATE POLICY "Admins and technicians can read evidences"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-evidences' AND
  (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN') OR
    EXISTS (SELECT 1 FROM technicians WHERE profile_id = auth.uid())
  )
);

-- Technicians can delete their ticket evidences
CREATE POLICY "Technicians can delete their ticket evidences"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'ticket-evidences' AND
  EXISTS (
    SELECT 1
    FROM ticket_evidences te
    JOIN tickets t ON t.id = te.ticket_id
    JOIN technicians tech ON tech.id = t.technician_id
    WHERE tech.profile_id = auth.uid()
    AND te.file_url = storage.objects.name
    AND t.status != 'RESOLVED'
  )
);

-- ============================================================================
-- STORAGE POLICIES - ticket-signatures
-- ============================================================================

-- Admins can upload signatures
CREATE POLICY "Admins can upload signatures"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'ticket-signatures' AND
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN')
);

-- Technicians can upload signatures
CREATE POLICY "Technicians can upload signatures"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'ticket-signatures' AND
  EXISTS (SELECT 1 FROM technicians WHERE profile_id = auth.uid())
);

-- Technicians can update (upsert) signatures
CREATE POLICY "Technicians can update signatures"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM ticket_signatures ts
    JOIN tickets t ON t.id = ts.ticket_id
    JOIN technicians tech ON tech.id = t.technician_id
    WHERE tech.profile_id = auth.uid()
    AND ts.signature_url = storage.objects.name
    AND t.status != 'RESOLVED'
  )
);

-- Admins and technicians can read signatures
CREATE POLICY "Admins and technicians can read signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN') OR
    EXISTS (SELECT 1 FROM technicians WHERE profile_id = auth.uid())
  )
);
