-- Add admin_notes to tickets table
-- Author: Generated by Claude Code
-- Date: 2026-08-14

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS admin_notes text;

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS idx_tickets_status_created ON tickets(status, created_at DESC);
