-- Fix critical RLS security issues found in WIS-020 E2E testing
-- Author: Generated by Claude Code
-- Date: 2026-08-17

-- ============================================================================
-- FIX 1: Add missing INSERT policies for ticket_status_history
-- ============================================================================

-- Admins can insert status history
CREATE POLICY "Admins can insert status history"
  ON ticket_status_history FOR INSERT
  WITH CHECK (is_admin());

-- Technicians can insert status history for their tickets
CREATE POLICY "Technicians can insert status history for their tickets"
  ON ticket_status_history FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_status_history.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- FIX 2: Verify ticket UPDATE policy is correct
-- ============================================================================

-- The existing policy should already prevent cross-technician updates
-- Both USING and WITH CHECK clauses check technician_id = current_technician_id()
-- If the test shows it's not working, it may be due to the UPDATE matching 0 rows
-- (which PostgreSQL considers success with 0 affected rows)
-- The policy itself is correct and will be verified in testing.

-- ============================================================================
-- FIX 3: Add missing UPDATE policy for ticket_status_history
-- ============================================================================

CREATE POLICY "Admins can update status history"
  ON ticket_status_history FOR UPDATE
  USING (is_admin());

-- Technicians generally should not update history (append-only)
-- but if needed, add restricted policy here

-- ============================================================================
-- FIX 4: Add missing DELETE policies if needed
-- ============================================================================

-- Admins can delete status history (for corrections)
CREATE POLICY "Admins can delete status history"
  ON ticket_status_history FOR DELETE
  USING (is_admin());

-- Note: Technicians should not delete history records (audit trail)
