-- Add customizable map markers for technicians
-- Author: Generated by Claude Code
-- Date: 2026-10-04
-- Feature: WIS-FEATURE-TECH-MARKERS-01

-- ============================================================================
-- ADD MARKER CUSTOMIZATION COLUMNS TO TECHNICIANS
-- ============================================================================

-- Add map_marker_icon column with default 'PERSON'
-- Valid values: CAR, VAN, MOTORCYCLE, PERSON
ALTER TABLE technicians
ADD COLUMN map_marker_icon VARCHAR(20) NOT NULL DEFAULT 'PERSON'
CHECK (map_marker_icon IN ('CAR', 'VAN', 'MOTORCYCLE', 'PERSON'));

-- Add map_marker_color column with default 'BLUE'
-- Valid values: BLUE, GREEN, ORANGE, PURPLE, RED, CYAN, AMBER, PINK
ALTER TABLE technicians
ADD COLUMN map_marker_color VARCHAR(20) NOT NULL DEFAULT 'BLUE'
CHECK (map_marker_color IN ('BLUE', 'GREEN', 'ORANGE', 'PURPLE', 'RED', 'CYAN', 'AMBER', 'PINK'));

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Optional: Add index if we need to filter/group by marker type in the future
-- Not strictly necessary for MVP but good practice
CREATE INDEX idx_technicians_map_marker_icon ON technicians(map_marker_icon);
CREATE INDEX idx_technicians_map_marker_color ON technicians(map_marker_color);

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON COLUMN technicians.map_marker_icon IS 'Visual identity icon type for technician map markers (CAR, VAN, MOTORCYCLE, PERSON)';
COMMENT ON COLUMN technicians.map_marker_color IS 'Visual identity color for technician map markers (BLUE, GREEN, ORANGE, PURPLE, RED, CYAN, AMBER, PINK)';

-- ============================================================================
-- NOTES
-- ============================================================================

-- Backward compatibility:
-- - All existing technicians will automatically get default values (PERSON, BLUE)
-- - No manual updates required
-- - RLS policies are unchanged (technicians table already has proper RLS)
-- - API endpoints need to be updated to accept these new fields

-- Usage:
-- Frontend will translate these semantic values to actual visual representations:
-- - Icons: Lucide React components (Car, Truck, Bike, User)
-- - Colors: Tailwind color classes or hex values from design system
