-- Fix auth trigger that was causing user creation to fail
-- Author: Generated by Claude Code
-- Date: 2026-08-17

-- Recreate handle_new_user function with better error handling
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_full_name text;
  user_phone text;
BEGIN
  -- Extract full_name from metadata, fallback to email username
  user_full_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    split_part(NEW.email, '@', 1)
  );

  -- Extract phone from metadata
  user_phone := NEW.raw_user_meta_data->>'phone';

  -- Create profile with TECHNICIAN role by default
  -- ADMIN role must be set manually via admin script
  INSERT INTO public.profiles (id, full_name, email, role, phone, is_active)
  VALUES (
    NEW.id,
    user_full_name,
    NEW.email,
    'TECHNICIAN',  -- No explicit cast, let PostgreSQL handle it
    user_phone,
    true
  )
  ON CONFLICT (id) DO NOTHING;  -- Prevent errors if profile already exists

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Log error but don't prevent user creation
  RAISE WARNING 'Error creating profile for user %: %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
