-- Initial schema for Wisper Logística MVP
-- Author: Generated by Claude Code
-- Date: 2026-08-14

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

-- UUID generation (gen_random_uuid is built-in from Postgres 13+)

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE user_role AS ENUM ('ADMIN', 'TECHNICIAN');

CREATE TYPE ticket_status AS ENUM (
  'PENDING',
  'ASSIGNED',
  'IN_REVIEW',
  'PAUSED',
  'RESOLVED',
  'CANCELLED'
);

-- ============================================================================
-- TABLES
-- ============================================================================

-- PROFILES
CREATE TABLE profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  role user_role NOT NULL,
  phone text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_profiles_role ON profiles(role);
CREATE INDEX idx_profiles_is_active ON profiles(is_active);

-- CLIENTS
CREATE TABLE clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text NOT NULL,
  reference text,
  latitude double precision,
  longitude double precision,
  phone text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_clients_is_active ON clients(is_active);
CREATE INDEX idx_clients_name ON clients(name);

-- TECHNICIANS
CREATE TABLE technicians (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid UNIQUE NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  zone text,
  vehicle text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_technicians_profile_id ON technicians(profile_id);
CREATE INDEX idx_technicians_is_active ON technicians(is_active);

-- TICKETS
CREATE SEQUENCE tickets_folio_seq START WITH 1000;

CREATE TABLE tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  folio bigint UNIQUE NOT NULL DEFAULT nextval('tickets_folio_seq'),
  client_id uuid NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
  technician_id uuid REFERENCES technicians(id) ON DELETE SET NULL,
  failure_type text NOT NULL,
  solution_text text,
  technician_notes text,
  priority smallint DEFAULT 3 NOT NULL CHECK (priority >= 1 AND priority <= 5),
  status ticket_status DEFAULT 'PENDING' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  assigned_at timestamptz,
  started_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz DEFAULT now() NOT NULL,
  close_reason text
);

CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_tickets_technician_id ON tickets(technician_id);
CREATE INDEX idx_tickets_created_at ON tickets(created_at DESC);
CREATE INDEX idx_tickets_client_id ON tickets(client_id);
CREATE INDEX idx_tickets_folio ON tickets(folio);

-- TICKET EVIDENCES
CREATE TABLE ticket_evidences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  type text NOT NULL,
  file_url text NOT NULL,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  latitude double precision,
  longitude double precision,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_ticket_evidences_ticket_id ON ticket_evidences(ticket_id);
CREATE INDEX idx_ticket_evidences_created_at ON ticket_evidences(created_at DESC);

-- TICKET STATUS HISTORY
CREATE TABLE ticket_status_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  previous_status ticket_status,
  new_status ticket_status NOT NULL,
  changed_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_ticket_status_history_ticket_id_created_at ON ticket_status_history(ticket_id, created_at DESC);

-- TICKET SIGNATURES
CREATE TABLE ticket_signatures (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid UNIQUE NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  signature_url text NOT NULL,
  signed_by_name text,
  latitude double precision,
  longitude double precision,
  signed_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_ticket_signatures_ticket_id ON ticket_signatures(ticket_id);

-- TECHNICIAN LOCATIONS
CREATE TABLE technician_locations (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  technician_id uuid NOT NULL REFERENCES technicians(id) ON DELETE CASCADE,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  accuracy double precision,
  recorded_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_technician_locations_technician_id_recorded_at ON technician_locations(technician_id, recorded_at DESC);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to check if user is admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'ADMIN'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get technician_id for current user
CREATE OR REPLACE FUNCTION current_technician_id()
RETURNS uuid AS $$
BEGIN
  RETURN (
    SELECT id FROM technicians
    WHERE profile_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Triggers for updated_at
CREATE TRIGGER set_updated_at_profiles
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at_clients
  BEFORE UPDATE ON clients
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at_technicians
  BEFORE UPDATE ON technicians
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at_tickets
  BEFORE UPDATE ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- Trigger for ticket status history
CREATE OR REPLACE FUNCTION log_ticket_status_change()
RETURNS TRIGGER AS $$
BEGIN
  -- On INSERT, log initial status
  IF TG_OP = 'INSERT' THEN
    INSERT INTO ticket_status_history (ticket_id, previous_status, new_status)
    VALUES (NEW.id, NULL, NEW.status);
    RETURN NEW;
  END IF;

  -- On UPDATE, log status change only if status actually changed
  IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO ticket_status_history (ticket_id, previous_status, new_status)
    VALUES (NEW.id, OLD.status, NEW.status);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER log_ticket_status_change_trigger
  AFTER INSERT OR UPDATE ON tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_ticket_status_change();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE technicians ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_evidences ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE technician_locations ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES - PROFILES
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all profiles"
  ON profiles FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert profiles"
  ON profiles FOR INSERT
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update all profiles"
  ON profiles FOR UPDATE
  USING (is_admin());

-- Technicians can view their own profile
CREATE POLICY "Technicians can view own profile"
  ON profiles FOR SELECT
  USING (id = auth.uid());

CREATE POLICY "Technicians can update own profile"
  ON profiles FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- ============================================================================
-- RLS POLICIES - CLIENTS
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all clients"
  ON clients FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert clients"
  ON clients FOR INSERT
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update clients"
  ON clients FOR UPDATE
  USING (is_admin());

-- Technicians can view clients for their tickets
CREATE POLICY "Technicians can view clients for their tickets"
  ON clients FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.client_id = clients.id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- RLS POLICIES - TECHNICIANS
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all technicians"
  ON technicians FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert technicians"
  ON technicians FOR INSERT
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update technicians"
  ON technicians FOR UPDATE
  USING (is_admin());

-- Technicians can view their own record
CREATE POLICY "Technicians can view own record"
  ON technicians FOR SELECT
  USING (profile_id = auth.uid());

-- ============================================================================
-- RLS POLICIES - TICKETS
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all tickets"
  ON tickets FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert tickets"
  ON tickets FOR INSERT
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update all tickets"
  ON tickets FOR UPDATE
  USING (is_admin());

-- Technicians can view their tickets
CREATE POLICY "Technicians can view their tickets"
  ON tickets FOR SELECT
  USING (technician_id = current_technician_id());

-- Technicians can update their tickets
CREATE POLICY "Technicians can update their tickets"
  ON tickets FOR UPDATE
  USING (technician_id = current_technician_id())
  WITH CHECK (technician_id = current_technician_id());

-- ============================================================================
-- RLS POLICIES - TICKET EVIDENCES
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all evidences"
  ON ticket_evidences FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert evidences"
  ON ticket_evidences FOR INSERT
  WITH CHECK (is_admin());

-- Technicians can view evidences for their tickets
CREATE POLICY "Technicians can view evidences for their tickets"
  ON ticket_evidences FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_evidences.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- Technicians can insert evidences for their tickets
CREATE POLICY "Technicians can insert evidences for their tickets"
  ON ticket_evidences FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_evidences.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- RLS POLICIES - TICKET STATUS HISTORY
-- ============================================================================

-- Admins can view all history
CREATE POLICY "Admins can view all status history"
  ON ticket_status_history FOR SELECT
  USING (is_admin());

-- Technicians can view history for their tickets
CREATE POLICY "Technicians can view history for their tickets"
  ON ticket_status_history FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_status_history.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- RLS POLICIES - TICKET SIGNATURES
-- ============================================================================

-- Admins can do everything
CREATE POLICY "Admins can view all signatures"
  ON ticket_signatures FOR SELECT
  USING (is_admin());

CREATE POLICY "Admins can insert signatures"
  ON ticket_signatures FOR INSERT
  WITH CHECK (is_admin());

-- Technicians can view signatures for their tickets
CREATE POLICY "Technicians can view signatures for their tickets"
  ON ticket_signatures FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_signatures.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- Technicians can insert signatures for their tickets
CREATE POLICY "Technicians can insert signatures for their tickets"
  ON ticket_signatures FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_signatures.ticket_id
        AND tickets.technician_id = current_technician_id()
    )
  );

-- ============================================================================
-- RLS POLICIES - TECHNICIAN LOCATIONS
-- ============================================================================

-- Admins can view all locations
CREATE POLICY "Admins can view all locations"
  ON technician_locations FOR SELECT
  USING (is_admin());

-- Technicians can view their own locations
CREATE POLICY "Technicians can view own locations"
  ON technician_locations FOR SELECT
  USING (technician_id = current_technician_id());

-- Technicians can insert their own locations
CREATE POLICY "Technicians can insert own locations"
  ON technician_locations FOR INSERT
  WITH CHECK (technician_id = current_technician_id());
