-- Fix storage RLS policies to prevent cross-technician access
-- Author: Generated by Claude Code
-- Date: 2026-08-17
-- Issue: WIS-020 found that any technician could read any evidence/signature

-- ============================================================================
-- FIX: ticket-evidences READ policy
-- ============================================================================

-- Drop overly permissive policy
DROP POLICY IF EXISTS "Admins and technicians can read evidences" ON storage.objects;

-- Admin can read all evidences
CREATE POLICY "Admins can read evidences"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-evidences' AND
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN')
);

-- Technicians can ONLY read evidences for their own tickets
CREATE POLICY "Technicians can read their ticket evidences"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-evidences' AND
  EXISTS (
    SELECT 1
    FROM ticket_evidences te
    JOIN tickets t ON t.id = te.ticket_id
    JOIN technicians tech ON tech.id = t.technician_id
    WHERE tech.profile_id = auth.uid()
    AND te.file_url = storage.objects.name
  )
);

-- ============================================================================
-- FIX: ticket-signatures READ policy
-- ============================================================================

-- Drop overly permissive policy
DROP POLICY IF EXISTS "Admins and technicians can read signatures" ON storage.objects;

-- Admin can read all signatures
CREATE POLICY "Admins can read signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'ADMIN')
);

-- Technicians can ONLY read signatures for their own tickets
CREATE POLICY "Technicians can read their ticket signatures"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'ticket-signatures' AND
  EXISTS (
    SELECT 1
    FROM ticket_signatures ts
    JOIN tickets t ON t.id = ts.ticket_id
    JOIN technicians tech ON tech.id = t.technician_id
    WHERE tech.profile_id = auth.uid()
    AND ts.signature_url = storage.objects.name
  )
);
