-- Add email to profiles for easier queries
-- Author: Generated by Claude Code
-- Date: 2026-08-14

-- Add email column to profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email text;

-- Create index on email
CREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);

-- Update handle_new_user function to save email
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_full_name text;
  user_phone text;
BEGIN
  -- Extract full_name from metadata, fallback to email username
  user_full_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    split_part(NEW.email, '@', 1)
  );

  -- Extract phone from metadata
  user_phone := NEW.raw_user_meta_data->>'phone';

  -- Create profile with TECHNICIAN role by default
  -- ADMIN role must be set manually via admin script
  INSERT INTO public.profiles (id, full_name, email, role, phone, is_active)
  VALUES (
    NEW.id,
    user_full_name,
    NEW.email,
    'TECHNICIAN'::user_role,
    user_phone,
    true
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
